#!/bin/sh

if [ "${STG_PROFILE:=dev}" = "dev" ]
then
    profile_dir="debug"
else
    profile_dir="$STG_PROFILE"
fi
if [ -n "$STG_TARGET" ]
then
    exec "$STG_ROOT/target/$STG_TARGET/$profile_dir/stg" "$@"
else
    exec "$STG_ROOT/target/$profile_dir/stg" "$@"
fi
