#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, make this file executable by "chmod +x post-update".

git repack -d
git update-server-info

# FTP upload
lftp ftp://your-ftp-site/stgit.git -u username,password -e " \
set ftp:list-empty-ok yes; \
echo Uploading objects; \
mirror -RLecv objects objects; \
echo Uploading refs; \
mirror -RLecv refs refs; \
echo Uploading info; \
mirror -RLecv info info; \
echo Uploading description; \
put description -o description; \
echo Uploading HEAD; \
put HEAD -o HEAD; \
exit"
