#!/usr/bin/env python
# -*- python -*-
import optparse, sys
import stgit.main
from stgit import argparse

def main():
    op = optparse.OptionParser()
    op.add_option('--asciidoc', metavar = 'CMD',
                  help = 'Print asciidoc documentation for a command')
    op.add_option('--commands', action = 'store_true',
                  help = 'Print list of all stg subcommands')
    options, args = op.parse_args()
    if args:
        op.error('Wrong number of arguments')
    if options.asciidoc:
        argparse.write_asciidoc(stgit.main.commands[options.asciidoc],
                                sys.stdout)
    elif options.commands:
        for cmd in sorted(stgit.main.commands.iterkeys()):
            print cmd
    else:
        op.error('No command')

if __name__ == '__main__':
    main()
