name: Rebase

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git config user.name "$(git log -1 --pretty=format:'%aN')"
    - run: git config user.email "$(git log -1 --pretty=format:'%aE')"
    - run: git fetch --prune --unshallow origin +refs/tags/*:refs/tags/*
    - run: git fetch https://github.com/stacked-git/stgit.git master
    - run: git rebase FETCH_HEAD
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
